const TOPIC = {
  SETUP_WEATHER: 'SETUP_WEATHER_BY_DATA',
  LOG: 'LOG_MESSAGE',
  BUILD_CURRENT_WEATHER: 'BUILD_CURRENT_WEATHER',
  BUILD_NEXT_DAYS: 'BUILD_NEXT_DAYS',
  INSERT_NEW_PROGRESS: 'INSERT_NEW_PROGRESS',
  FINISH_PROGRESS: 'FINISH_PROGRESS',
  ENABLE_PROGRESS: 'CLOSE_PROGRESS'
}

export default TOPIC
